---
- name: Install required python modules for Docker
  pip:
    name: "{{ item.name }}"
    state: present
  with_items:
  - { name: jsondiff }

- name: Install required python modules for Docker (with specific versions)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker-py, version: 1.10.6 }

- name: Create an overlay network
  docker_network:
    name: '{{ docker_network_name }}'
    driver: overlay
    state: present

- name: Remove monitoring stack
  docker_stack:
    name: monitoring
    state: absent

- import_tasks: prometheus.yml

- import_tasks: alertmanager.yml

- import_tasks: grafana.yml

- name: Write out docker-compose-monitoring.yml template
  template:
    src: docker-compose-monitoring.yml.j2
    dest: '{{ temporary_directory }}/docker-compose-monitoring.yml'

- name: Deploy monitoring stack swarm
  docker_stack:
    state: present
    name: monitoring
    compose:
      - "{{ temporary_directory }}/docker-compose-monitoring.yml"
    with_registry_auth: yes